######################## default configuration ####################
baseURL = "https://www.tvuj-terapeut.cz/"
title = "Mgr. Romana Svíbová"
theme = "bigspring"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu

[[menu.main]]
name = "Úvod"
URL = "/"
weight = 1

[[menu.main]]
name = "Terapie"
URL = "/terapie"
weight = 2

[[menu.main]]
name = "Poradenství"
URL = "/poradenstvi"
weight = 3

[[menu.main]]
name = "Hubnutí"
URL = "/redukce_hmotnosti"
weight = 4

[[menu.main]]
name = "Hovory o sádle"
URL = "/hovory_o_sadle"
weight = 5

[[menu.main]]
name = "Ceník"
URL = "/cenik"
weight = 6

[[menu.main]]
name = "Kontakt"
URL = "/contact"
weight = 7

# footer menu left
[[menu.footer_left]]
name = "Terapie"
URL = "/terapie"
weight = 1

[[menu.footer_left]]
name = "Poradenství"
URL = "/poradenstvi"
weight = 2

[[menu.footer_left]]
name = "Podpůrné skupiny"
URL = "/skupiny"
weight = 3

[[menu.footer_left]]
name = "Hubnutí"
URL = "/redukce_hmotnosti"
weight = 4

# footer menu middle
[[menu.footer_middle]]
name = "O mně"
URL = "/omne"
weight = 1

[[menu.footer_middle]]
name = "Důležité informace"
URL = "/dulezite"
weight = 2

[[menu.footer_middle]]
name = "Ceník"
URL = "/cenik"
weight = 3

[[menu.footer_middle]]
name = "Kontakt"
URL = "contact"
weight = 4

#################### default parameters ################################
[params]
logo = "images/preview2.jpg"
logo_width = "0px"
# Meta data
description = "Tvůj terapeut Romana Svíbová"
author = "OndřejBaše"
# contact form action
contact_form_action = "/diky" # contact form works with https://formspree.io
googleMapsAPIKey = "AIzaSyDeU36-CXGJ2wPZ3MZWN_bpdNQ190MMfcM"

########### footer content ##########
footer_menu_left = "Služby"
footer_menu_middle = "Terapeut"
footer_menu_right = ""
footer_content = "<b>Mgr. Romana Svíbová</b> <br><br>Soukromá terapie a poradenství pro dospívající a dospělé v Hradci Králové, párová terapie, rodinná terapie"
# copyright
copyright = "Created by: [Ondřej Baše](https://www.ondrejbase.cz)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
# [params.navigation_button]
# enable = true
# label = "Kontakt"
# link = "contact"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/TvujTerapeutHradec"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/mgr-romana-svíbová-9b0421204/"

